format = "dothoard-manifest"
version = 1

[[sources]]
path = ".bashrc"
ignore = []

[[sources]]
path = ".zshrc"
ignore = []

[[sources]]
path = ".config/hypr"
ignore = []

[[sources]]
path = ".config/nvim"
ignore = []

[[sources]]
path = ".config/fish"
ignore = []

[[sources]]
path = ".config/kitty"
ignore = []
