color0 #49454e
color1 #ffb4ab
color2 #d5bbfc
color3 #cec2db
color4 #f1b7c3
color5 #d5bbfc
color6 #cec2db
color7 #e7e0e8
color8 #958e99
color9 #ffb4ab
color10 #d5bbfc
color11 #cec2db
color12 #f1b7c3
color13 #d5bbfc
color14 #cec2db
color15 #e7e0e8

cursor                #e7e0e8
cursor_text_color     #151218
background            #151218
foreground            #e7e0e8
selection_foreground  #cbc4cf
selection_background  #49454e
active_border_color   #d5bbfc
inactive_border_color #49454e
url_color             #d5bbfc

active_tab_foreground   #3a255b
active_tab_background   #d5bbfc
inactive_tab_foreground #cbc4cf
inactive_tab_background #49454e
cursor_trail_color      #cbc4cf
