color0 #41484d
color1 #ffb4ab
color2 #91cef5
color3 #b6c9d8
color4 #ccc1e9
color5 #91cef5
color6 #b6c9d8
color7 #dfe3e7
color8 #8b9198
color9 #ffb4ab
color10 #91cef5
color11 #b6c9d8
color12 #ccc1e9
color13 #91cef5
color14 #b6c9d8
color15 #dfe3e7

cursor                #dfe3e7
cursor_text_color     #0f1417
background            #0f1417
foreground            #dfe3e7
selection_foreground  #c1c7ce
selection_background  #41484d
active_border_color   #91cef5
inactive_border_color #41484d
url_color             #91cef5

active_tab_foreground   #00344b
active_tab_background   #91cef5
inactive_tab_foreground #c1c7ce
inactive_tab_background #41484d
cursor_trail_color      #c1c7ce
