color0 #43474e
color1 #ffb4ab
color2 #a6c8ff
color3 #bdc7dc
color4 #dabde2
color5 #a6c8ff
color6 #bdc7dc
color7 #e1e2e9
color8 #8d9199
color9 #ffb4ab
color10 #a6c8ff
color11 #bdc7dc
color12 #dabde2
color13 #a6c8ff
color14 #bdc7dc
color15 #e1e2e9

cursor                #e1e2e9
cursor_text_color     #111318
background            #111318
foreground            #e1e2e9
selection_foreground  #c4c6cf
selection_background  #43474e
active_border_color   #a6c8ff
inactive_border_color #43474e
url_color             #a6c8ff

active_tab_foreground   #02315f
active_tab_background   #a6c8ff
inactive_tab_foreground #c4c6cf
inactive_tab_background #43474e
cursor_trail_color      #c4c6cf
