return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = true,
      float = {
        transparent = true,
      },
      term_colors = true,
      color_overrides = {
        mocha = {
          base = "#111318",
          mantle = "#0d0f13",
          crust = "#090b0e",
          text = "#e2e2e9",
          subtext1 = "#c4c6d0",
          subtext0 = "#9a9ca5",
          overlay2 = "#8e9099",
          overlay1 = "#767980",
          overlay0 = "#62656c",
          surface2 = "#44474f",
          surface1 = "#3a3d45",
          surface0 = "#2c2f36",
          blue = "#adc6ff",
          lavender = "#debcdf",
          mauve = "#debcdf",
          sapphire = "#adc6ff",
          sky = "#bfc6dc",
          teal = "#bfc6dc",
          green = "#adc6ff",
          yellow = "#bfc6dc",
          peach = "#bfc6dc",
          maroon = "#ffb4ab",
          red = "#ffb4ab",
          pink = "#debcdf",
          flamingo = "#ffb4ab",
          rosewater = "#c4c6d0",
        },
      },
      highlight_overrides = {
        mocha = {
          CursorLine = { bg = "#1c1f26" },
          CursorLineNr = { fg = "#e2e2e9" },
          Visual = { bg = "#44474f", fg = "#e2e2e9" },
          VisualNOS = { bg = "#44474f" },
          Search = { bg = "#44474f", fg = "#adc6ff" },
          IncSearch = { bg = "#adc6ff", fg = "#111318" },
          MatchParen = { bg = "#44474f" },
          NonText = { fg = "#3a3d45" },
          WinSeparator = { fg = "#2c2f36" },
          Comment = { fg = "#8e9099" },
          ["@comment"] = { fg = "#8e9099" },
        },
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin-mocha",
    },
  },
}